---
- hosts: tag_Name_covid_k8s
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: tag_Name_covid_k8s_worker_1, tag_Name_covid_k8s_worker_2
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['MASTER_IP_ADDRESS'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
