FROM centos:latest
RUN yum install python3  python3-devel   gcc-c++ -y && \
    python3 -m pip install --upgrade --force-reinstall pip && \
    yum install sudo -y && \
    yum install --assumeyes  python3-pip && \
    pip install keras && \
    pip install tensorflow --no-cache-dir  tensorflow && \
    pip install --upgrade pip tensorflow && \
    pip3 install flask && \
    pip3 install joblib && \
    pip3 install sklearn && \
    mkdir  /covid_app &&  \
    mkdir /covid_app/templates
COPY RandomForest_Covid_Prediction.h5    /covid_app
COPY  app.py  /covid_app
COPY  myform.html  /covid_app/templates
COPY  results.html   /covid_app/templates
EXPOSE  4444
WORKDIR  /covid_app
CMD export FLASK_APP=app.py
ENTRYPOINT flask  run --host=0.0.0.0    --port=4444
